name: GitActions Demo1
on: push
jobs:
  GitActions-demo-job:
    name: Demo Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a environment
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: GilDong
          LAST_NAME: HONG
          AWS_JOB_NAME: gildong.hong
        run:
          echo $MY_VAR $FIRST_NAME $LAST_NAME
          echo $MY_VAR $AWS_JOB_NAME
